CREATE TABLE `adv_matchlines` (
  `matchid` bigint(20) UNSIGNED NOT NULL,
  `playerid` bigint(20) NOT NULL,
  `heroid` smallint(5) UNSIGNED NOT NULL,
  `lh_at10` mediumint(9) UNSIGNED NOT NULL,
  `isCore` tinyint(1) NOT NULL,
  `lane` tinyint(3) UNSIGNED NOT NULL,
  `role` tinyint(3) UNSIGNED NOT NULL,
  `lane_won` tinyint(3) UNSIGNED NOT NULL,
  `efficiency_at10` float NOT NULL,
  `wards` smallint(5) UNSIGNED NOT NULL,
  `sentries` smallint(5) UNSIGNED NOT NULL,
  `couriers_killed` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `roshans_killed` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `multi_kill` tinyint(3) UNSIGNED NOT NULL DEFAULT '0',
  `streak` tinyint(3) UNSIGNED NOT NULL DEFAULT '0',
  `stacks` tinyint(4) NOT NULL DEFAULT '0',
  `time_dead` int(10) UNSIGNED NOT NULL,
  `buybacks` smallint(5) NOT NULL DEFAULT '0',
  `wards_destroyed` smallint(5) UNSIGNED NOT NULL DEFAULT '0',
  `pings` int(10) NOT NULL DEFAULT '0',
  `stuns` float NOT NULL,
  `teamfight_part` float NOT NULL,
  `damage_taken` int(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`matchid`,`playerid`),
  KEY `advmatchlines_matchid_heroid_IDX` (`matchid`,`heroid`) USING BTREE,
  KEY `advmatchlines_heroid_iscore_IDX` (`heroid`,`isCore`) USING BTREE,
  KEY `advmatchlines_heroid_lane_IDX` (`heroid`,`lane`) USING BTREE,
  KEY `advmatchlines_playerid_iscore_IDX` (`playerid`,`isCore`) USING BTREE,
  KEY `advmatchlines_playerid_heroid_IDX` (`playerid`,`heroid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
