CREATE TABLE `fantasy_mvp_points` (
  `matchid` bigint(20) UNSIGNED NOT NULL,
  `playerid` bigint(20) NOT NULL,
  `heroid` smallint(6) NOT NULL,
  `total_points` DOUBLE NOT NULL,
  `kills` FLOAT NOT NULL,
  `deaths` FLOAT NOT NULL,
  `assists` FLOAT NOT NULL,
  `creeps` FLOAT NOT NULL,
  `gpm` FLOAT NOT NULL,
  `xpm` FLOAT NOT NULL,
  `obs_placed` FLOAT NOT NULL,
  `stacks` FLOAT NOT NULL,
  `stuns` FLOAT NOT NULL,
  `teamfight_part` FLOAT NOT NULL,
  `damage` FLOAT NOT NULL,
  `healing` FLOAT NOT NULL,
  `damage_taken` FLOAT NOT NULL,
  `hero_damage_taken_bonus` FLOAT NOT NULL,
  `hero_damage_taken_penalty` FLOAT NOT NULL,
  `tower_damage` FLOAT NOT NULL,
  `obs_kills` FLOAT NOT NULL,
  `cour_kills` FLOAT NOT NULL,
  `buybacks` FLOAT NOT NULL,
  PRIMARY KEY (`matchid`,`playerid`),
  KEY `fantasy_breakdown_matchid_heroid_IDX` (`matchid`,`heroid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
