CREATE TABLE `matchlines` (
  `matchid` bigint(20) UNSIGNED NOT NULL,
  `playerid` bigint(20) NOT NULL,
  `heroid` smallint(6) NOT NULL,
  `variant` SMALLINT(6) UNSIGNED DEFAULT null NULL,
  `level` tinyint(3) UNSIGNED NOT NULL,
  `isRadiant` tinyint(1) NOT NULL,
  `kills` smallint(6) NOT NULL,
  `deaths` smallint(6) NOT NULL,
  `assists` smallint(6) NOT NULL,
  `networth` mediumint(9) NOT NULL,
  `gpm` mediumint(9) NOT NULL,
  `xpm` mediumint(9) NOT NULL,
  `heal` mediumint(9) NOT NULL,
  `heroDamage` mediumint(9) NOT NULL,
  `towerDamage` mediumint(9) NOT NULL,
  `lastHits` smallint(6) NOT NULL,
  `denies` smallint(6) NOT NULL,
  PRIMARY KEY (`matchid`,`playerid`),
  KEY `matchlines_matchid_heroid_IDX` (`matchid`,`heroid`) USING BTREE,
  KEY `matchlines_heroid_isradiant_IDX` (`heroid`,`isRadiant`) USING BTREE,
  KEY `matchlines_playerid_isradiant_IDX` (`playerid`,`isRadiant`) USING BTREE,
  KEY `matchlines_playerid_heroid_IDX` (`playerid`,`heroid`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
